// Daily Vocabulary Centre — Packs 3-4
window.VOCAB_PACKS = (window.VOCAB_PACKS || []).concat([
{
  id: 3, title: "Precision & Nuance", subtitle: "Say exactly what you mean", emoji: "🔬", color: "#a78bfa",
  words: [
    { id: "p3w1", word: "ambiguous", pos: "adjective", ipa: "/æmˈbɪɡjuəs/", emoji: "🌫️",
      def: "having more than one possible meaning; unclear",
      ex: "The instructions were ambiguous, so students interpreted them differently.",
      collocs: ["an ambiguous result", "deliberately ambiguous"],
      family: "ambiguity (n) · ambiguous (adj) · ambiguously (adv)",
      tip: "Precise writing avoids ambiguity: make your position impossible to misread." },
    { id: "p3w2", word: "explicit", pos: "adjective", ipa: "/ɪkˈsplɪsɪt/", emoji: "🔍",
      def: "stated clearly and directly, leaving no room for confusion",
      ex: "The rubric makes explicit what examiners expect in each paragraph.",
      collocs: ["explicit instructions", "make something explicit"],
      family: "explicitly (adv) · explicitness (n) · implicit (opposite adj)",
      tip: "Opposite of implicit. Use 'explicit' when something is stated outright." },
    { id: "p3w3", word: "implicit", pos: "adjective", ipa: "/ɪmˈplɪsɪt/", emoji: "💭",
      def: "suggested without being directly stated",
      ex: "The author makes an implicit assumption that all readers share her values.",
      collocs: ["an implicit assumption", "implicit meaning"],
      family: "implicitly (adv) · implicitness (n)",
      tip: "In reading questions: implicit = inferred, not stated. Never quote a line for an 'implicit' answer." },
    { id: "p3w4", word: "nuanced", pos: "adjective", ipa: "/ˈnuːɑːnst/", emoji: "🎛️",
      def: "showing small but important differences",
      ex: "Her nuanced answer acknowledged both sides before choosing one.",
      collocs: ["a nuanced view", "a nuanced understanding"],
      family: "nuance (n) · nuanced (adj)",
      tip: "Marks C1-level evaluation: show you understand the shades, not just black and white." },
    { id: "p3w5", word: "subtle", pos: "adjective", ipa: "/ˈsʌtl/", emoji: "🫧",
      def: "not obvious; delicate and slight",
      ex: "There is a subtle difference between confidence and arrogance.",
      collocs: ["a subtle difference", "subtle changes", "a subtle shift"],
      family: "subtly (adv) · subtlety (n) · subtle (adj)",
      tip: "The 'b' is silent: /ˈsʌtl/. Compare subtle vs. obvious." },
    { id: "p3w6", word: "precise", pos: "adjective", ipa: "/prɪˈsaɪs/", emoji: "📐",
      def: "exact, accurate, and clearly stated",
      ex: "Use precise numbers: '47 percent' is stronger than 'many'.",
      collocs: ["precise language", "to be precise", "at that precise moment"],
      family: "precision (n) · precise (adj) · precisely (adv)",
      tip: "Your L26 theme. Replace vague words (many, good, bad) with precise ones." },
    { id: "p3w7", word: "vague", pos: "adjective", ipa: "/veɪɡ/", emoji: "☁️",
      def: "not clear or exact; imprecise",
      ex: "A vague thesis ('technology is bad') cannot be supported well.",
      collocs: ["a vague idea", "vague promises", "deliberately vague"],
      family: "vaguely (adv) · vagueness (n)",
      tip: "Vague ➜ precise upgrade: 'bad' ➜ 'detrimental', 'important' ➜ 'paramount'." },
    { id: "p3w8", word: "inherent", pos: "adjective", ipa: "/ɪnˈhɪrənt/", emoji: "🧬",
      def: "existing as a natural and permanent part of something",
      ex: "There are inherent risks in relying on a single source of data.",
      collocs: ["inherent in", "an inherent problem", "inherent value"],
      family: "inherently (adv) · inherence (n)",
      tip: "Pattern: 'inherent in something'. Strong for analytical comments." },
    { id: "p3w9", word: "arbitrary", pos: "adjective", ipa: "/ˈɑːrbɪtreri/", emoji: "🎲",
      def: "based on personal choice or chance rather than reason",
      ex: "The deadline felt arbitrary rather than connected to real learning goals.",
      collocs: ["an arbitrary decision", "seem arbitrary"],
      family: "arbitrarily (adv) · arbitrariness (n)",
      tip: "Perfect for critiquing policies: 'The rule is arbitrary because…'." },
    { id: "p3w10", word: "unequivocal", pos: "adjective", ipa: "/ˌʌnɪˈkwɪvəkl/", emoji: "🎯",
      def: "completely clear and without doubt",
      ex: "The evidence provides unequivocal support for the new policy.",
      collocs: ["unequivocal support", "unequivocal evidence"],
      family: "unequivocally (adv) · equivocal (adj)",
      tip: "A C2 gem. Means so clear it cannot be doubted. Opposite: equivocal." },
    { id: "p3w11", word: "distortion", pos: "noun", ipa: "/dɪˈstɔːrʃn/", emoji: "🪞",
      def: "a change that makes something less accurate or true",
      ex: "Selective statistics create a distortion of the real situation.",
      collocs: ["a distortion of the facts", "gross distortion"],
      family: "distort (v) · distorted (adj) · distortion (n)",
      tip: "Use when analysing misleading data or media coverage." },
    { id: "p3w12", word: "connotation", pos: "noun", ipa: "/ˌkɑːnəˈteɪʃn/", emoji: "🎨",
      def: "an idea or feeling a word suggests beyond its literal meaning",
      ex: "'Cheap' and 'affordable' share a meaning but differ in connotation.",
      collocs: ["a negative connotation", "carry connotations"],
      family: "connote (v) · connotative (adj)",
      tip: "Strong for vocabulary-precision analysis: 'The word X carries a … connotation'." },
    { id: "p3w13", word: "oversimplify", pos: "verb", ipa: "/ˌoʊvərˈsɪmplɪfaɪ/", emoji: "➖",
      def: "to describe something so simply that important details are lost",
      ex: "It would oversimplify the debate to blame only social media.",
      collocs: ["oversimplify the issue", "a dangerous oversimplification"],
      family: "oversimplification (n) · oversimplified (adj)",
      tip: "Use in counterargument sentences: 'This view oversimplifies the problem.'" },
    { id: "p3w14", word: "perpetuate", pos: "verb", ipa: "/pərˈpetʃueɪt/", emoji: "🔁",
      def: "to make something continue, especially something negative",
      ex: "Publishing only successful studies perpetuates a distorted picture of science.",
      collocs: ["perpetuate a myth", "perpetuate inequality"],
      family: "perpetuation (n) · perpetuated (adj)",
      tip: "Spelling: -pet- (pet). Often collocates with myths, stereotypes, inequality." },
    { id: "p3w15", word: "depict", pos: "verb", ipa: "/dɪˈpɪkt/", emoji: "🖼️",
      def: "to represent or describe something in words or images",
      ex: "The chart depicts the rise in renewable energy use since 2010.",
      collocs: ["depict a trend", "be depicted as"],
      family: "depiction (n) · depicted (adj)",
      tip: "Useful for Task 1 and reading: 'the diagram depicts…'." }
  ]
},
{
  id: 4, title: "Argument & Evidence", subtitle: "Win the debate logically", emoji: "⚖️", color: "#f59e0b",
  words: [
    { id: "p4w1", word: "substantiate", pos: "verb", ipa: "/səbˈstænʃieɪt/", emoji: "🏛️",
      def: "to provide evidence that proves a claim is true",
      ex: "The author fails to substantiate her claim with data.",
      collocs: ["substantiate a claim", "substantiate an argument", "evidence to substantiate"],
      family: "substantiation (n) · substantial (adj) · substantiated (adj)",
      tip: "A core exam word in your journals — use it in conclusions and critiques." },
    { id: "p4w2", word: "refute", pos: "verb", ipa: "/rɪˈfjuːt/", emoji: "🥊",
      def: "to prove that a statement or idea is wrong",
      ex: "New evidence refutes the earlier assumption that class size does not matter.",
      collocs: ["refute an argument", "refute a claim", "hard to refute"],
      family: "refutation (n) · refutable (adj)",
      tip: "Stronger than 'disagree with': refute = prove wrong with evidence." },
    { id: "p4w3", word: "concede", pos: "verb", ipa: "/kənˈsiːd/", emoji: "🤝",
      def: "to admit that a point is true before disagreeing with it",
      ex: "I concede that online courses are flexible, but they lack real interaction.",
      collocs: ["concede that", "concede a point"],
      family: "concession (n) · conceding (adj)",
      tip: "The classic English concession move: concede ➜ counter. Already in your toolbox!" },
    { id: "p4w4", word: "compelling", pos: "adjective", ipa: "/kəmˈpelɪŋ/", emoji: "🧲",
      def: "very convincing and impossible to ignore",
      ex: "She presented a compelling case for stricter emissions rules.",
      collocs: ["a compelling argument", "compelling evidence", "a compelling reason"],
      family: "compel (v) · compellingly (adv)",
      tip: "High-value evaluative word: 'The most compelling explanation is…'." },
    { id: "p4w5", word: "outweigh", pos: "verb", ipa: "/ˌaʊtˈweɪ/", emoji: "⚖️",
      def: "to be more important or greater than something else",
      ex: "The benefits of early intervention clearly outweigh the costs.",
      collocs: ["benefits outweigh", "outweigh the disadvantages", "far outweigh"],
      family: "outweighing (adj)",
      tip: "Perfect for 'balanced view' conclusions in Academic Discussion." },
    { id: "p4w6", word: "valid", pos: "adjective", ipa: "/ˈvælɪd/", emoji: "✅",
      def: "based on sound reasoning; legally or logically acceptable",
      ex: "Both sides make valid points about remote work.",
      collocs: ["a valid point", "a valid argument", "valid concerns"],
      family: "validity (n) · validate (v) · validly (adv)",
      tip: "Use to acknowledge the other side without abandoning your position." },
    { id: "p4w7", word: "credible", pos: "adjective", ipa: "/ˈkredəbl/", emoji: "🎖️",
      def: "able to be believed or trusted",
      ex: "The study is credible because it used a large, random sample.",
      collocs: ["a credible source", "credible evidence", "establish credibility"],
      family: "credibility (n) · credibly (adv)",
      tip: "Connect to your L18 collocation 'establish credibility'." },
    { id: "p4w8", word: "warrant", pos: "verb", ipa: "/ˈwɔːrənt/", emoji: "📜",
      def: "to justify or make something seem reasonable",
      ex: "The results warrant further investigation.",
      collocs: ["warrant attention", "warrant further study"],
      family: "warrant (n/v) · warranted (adj)",
      tip: "Formal verb: 'The evidence does not warrant such a strong conclusion.'" },
    { id: "p4w9", word: "undermine", pos: "verb", ipa: "/ˌʌndərˈmaɪn/", emoji: "⛏️",
      def: "to weaken something gradually",
      ex: "Small inconsistencies undermine the credibility of the whole argument.",
      collocs: ["undermine an argument", "undermine confidence", "seriously undermine"],
      family: "undermining (adj)",
      tip: "Use for critique: which weakness weakens which claim?" },
    { id: "p4w10", word: "bolster", pos: "verb", ipa: "/ˈboʊlstər/", emoji: "🛡️",
      def: "to support or strengthen something",
      ex: "Additional data would bolster the author's conclusion.",
      collocs: ["bolster a claim", "bolster support", "bolster the argument"],
      family: "bolstered (adj)",
      tip: "The positive twin of 'undermine'. Great for recommendations." },
    { id: "p4w11", word: "counterargument", pos: "noun", ipa: "/ˈkaʊntərɑːrɡjumənt/", emoji: "↩️",
      def: "an argument against your main position",
      ex: "Address one counterargument to show your view is balanced.",
      collocs: ["address a counterargument", "acknowledge the counterargument"],
      family: "counterargue (v)",
      tip: "Structure: counterargument ➜ your rebuttal ➜ conclusion." },
    { id: "p4w12", word: "assertion", pos: "noun", ipa: "/əˈsɜːrʃn/", emoji: "📢",
      def: "a confident statement, often without proof",
      ex: "The essay is full of assertions but lacks supporting evidence.",
      collocs: ["make an assertion", "an unsupported assertion"],
      family: "assert (v) · assertive (adj) · assertion (n)",
      tip: "Critique word: an assertion is a claim that still needs proof." },
    { id: "p4w13", word: "premise", pos: "noun", ipa: "/ˈpremɪs/", emoji: "🧱",
      def: "a basic idea that an argument is built on",
      ex: "The argument rests on the premise that students learn best in silence.",
      collocs: ["a false premise", "on the premise that", "challenge the premise"],
      family: "premised (adj)",
      tip: "Ask: is the premise true? If not, the argument fails — great exam analysis." },
    { id: "p4w14", word: "bias", pos: "noun", ipa: "/ˈbaɪəs/", emoji: "🧭",
      def: "an unfair preference that affects judgement",
      ex: "The survey suffers from bias because only volunteers responded.",
      collocs: ["selection bias", "confirmation bias", "show bias"],
      family: "biased (adj) · bias (v/n)",
      tip: "Reading questions love bias: always ask who is left out of the sample." },
    { id: "p4w15", word: "plausible", pos: "adjective", ipa: "/ˈplɔːzəbl/", emoji: "🤔",
      def: "seeming reasonable or likely to be true",
      ex: "Her explanation is plausible, but it needs more evidence.",
      collocs: ["a plausible explanation", "perfectly plausible", "sound plausible"],
      family: "plausibility (n) · plausibly (adv)",
      tip: "Useful middle ground: plausible = believable but not yet proven." }
  ]
}
]);
