// Daily Vocabulary Centre — Packs 1-2
window.VOCAB_PACKS = (window.VOCAB_PACKS || []).concat([
{
  id: 1, title: "Flow & Cohesion", subtitle: "Transitions & connectors", emoji: "🔗", color: "#38bdf8",
  words: [
    { id: "p1w1", word: "nevertheless", pos: "adverb", ipa: "/ˌnevəðəˈles/", emoji: "↩️",
      def: "in spite of that; despite what was just said",
      ex: "Online courses are convenient. Nevertheless, they cannot replace the energy of a live seminar.",
      collocs: ["Nevertheless, the evidence suggests…", "a small nevertheless important step"],
      family: "nevertheless (adv)",
      tip: "Sentence-initial + comma, or mid-sentence between commas: The results, nevertheless, were clear." },
    { id: "p1w2", word: "furthermore", pos: "adverb", ipa: "/ˌfɜːrðərˈmɔːr/", emoji: "➕",
      def: "in addition; used to add another point that supports the same idea",
      ex: "The program reduces costs. Furthermore, it improves student satisfaction.",
      collocs: ["Furthermore, it should be noted…", "and furthermore"],
      family: "further (adj) · furthermore (adv)",
      tip: "Stronger and more formal than 'also'. Use to stack a second reason." },
    { id: "p1w3", word: "consequently", pos: "adverb", ipa: "/ˈkɑːnsəkwentli/", emoji: "⛓️",
      def: "as a result; because of what was just described",
      ex: "The library extended its hours. Consequently, more students studied on campus.",
      collocs: ["Consequently, the results changed", "consequently fail to meet the deadline"],
      family: "consequence (n) · consequent (adj) · consequently (adv)",
      tip: "The most common 'result' transition in academic writing. Don't confuse with 'subsequently' (time, not cause)." },
    { id: "p1w4", word: "moreover", pos: "adverb", ipa: "/mɔːrˈoʊvər/", emoji: "📶",
      def: "in addition to what has been said; used to add a stronger point",
      ex: "The policy saves money. Moreover, it protects the most vulnerable students.",
      collocs: ["Moreover, it is important to note", "moreover, the data show"],
      family: "more (adj) · moreover (adv)",
      tip: "Like 'furthermore', but often introduces an even stronger argument." },
    { id: "p1w5", word: "nonetheless", pos: "adverb", ipa: "/ˌnʌnðəˈles/", emoji: "🔄",
      def: "despite that; even so",
      ex: "The sample was small. Nonetheless, the findings were consistent with earlier research.",
      collocs: ["Nonetheless, caution is needed", "nonetheless significant"],
      family: "nonetheless (adv)",
      tip: "Slightly more formal than 'nevertheless'. Swap them to avoid repeating the same transition." },
    { id: "p1w6", word: "conversely", pos: "adverb", ipa: "/ˈkɑːnvɜːrsli/", emoji: "↔️",
      def: "from the opposite point of view; used when the reverse is also true",
      ex: "Cities with more green space report happier residents. Conversely, crowded districts show higher stress levels.",
      collocs: ["Conversely, one could argue", "and conversely"],
      family: "converse (adj/n) · conversely (adv)",
      tip: "Use when the two halves of your argument are mirror images, not just different." },
    { id: "p1w7", word: "accordingly", pos: "adverb", ipa: "/əˈkɔːrdɪŋli/", emoji: "🎯",
      def: "in a way that is appropriate to what has been said; therefore",
      ex: "The deadline was moved. Accordingly, the team adjusted its schedule.",
      collocs: ["adjust accordingly", "act accordingly"],
      family: "according (prep) · accordingly (adv)",
      tip: "Strong in email conclusions: 'I would appreciate it if you could respond accordingly.'" },
    { id: "p1w8", word: "subsequently", pos: "adverb", ipa: "/ˈsʌbsɪkwəntli/", emoji: "⏭️",
      def: "after something else happened; later in time",
      ex: "The university introduced free tutoring, and subsequently its pass rate rose by 12 percent.",
      collocs: ["subsequently announced", "was subsequently replaced"],
      family: "subsequent (adj) · subsequently (adv)",
      tip: "Time order only. If you mean cause, use 'consequently'. This is a classic TOEFL mix-up." },
    { id: "p1w9", word: "hence", pos: "adverb", ipa: "/hens/", emoji: "💡",
      def: "for this reason; therefore (often used with a noun phrase)",
      ex: "The data were incomplete; hence the cautious conclusion.",
      collocs: ["hence the need for", "hence the conclusion that"],
      family: "hence (adv)",
      tip: "Often joins a short noun phrase, sometimes with just a comma or semicolon." },
    { id: "p1w10", word: "thus", pos: "adverb", ipa: "/ðʌs/", emoji: "🧩",
      def: "as a result; in this way",
      ex: "The survey was anonymous; thus, honest responses were more likely.",
      collocs: ["thus, it can be concluded", "thus creating"],
      family: "thus (adv)",
      tip: "Very common in conclusions. Follow it with a comma when it starts a sentence." },
    { id: "p1w11", word: "cohesion", pos: "noun", ipa: "/koʊˈhiːʒn/", emoji: "🧲",
      def: "the quality of ideas sticking together logically",
      ex: "Transition words give an essay cohesion, linking each paragraph to the next.",
      collocs: ["improve cohesion", "cohesion between paragraphs"],
      family: "cohesive (adj) · cohesively (adv) · cohesion (n)",
      tip: "Cohesion = linking devices; coherence = overall clarity of argument. Examiners care about both." },
    { id: "p1w12", word: "signpost", pos: "noun/verb", ipa: "/ˈsaɪnpoʊst/", emoji: "🪧",
      def: "a word or phrase that tells the reader where the argument is going",
      ex: "Phrases like 'firstly' and 'in contrast' act as signposts for the reader.",
      collocs: ["clear signposts", "signpost the structure"],
      family: "signpost (n/v) · signposting (n)",
      tip: "Signposting is expected in academic writing: First, … / In contrast, … / To conclude, …" },
    { id: "p1w13", word: "seamless", pos: "adjective", ipa: "/ˈsiːmləs/", emoji: "➰",
      def: "smooth and continuous, with no awkward gaps",
      ex: "The lecturer delivered a seamless argument from introduction to conclusion.",
      collocs: ["a seamless transition", "seamless integration"],
      family: "seamlessly (adv) · seamless (adj)",
      tip: "Great word for describing flow: 'a seamless connection between ideas'." },
    { id: "p1w14", word: "chronological", pos: "adjective", ipa: "/ˌkrɑːnəˈlɑːdʒɪkl/", emoji: "🕰️",
      def: "arranged in the order in which events happened",
      ex: "A chronological structure works best when you describe a sequence of events.",
      collocs: ["chronological order", "in chronological sequence"],
      family: "chronology (n) · chronological (adj) · chronologically (adv)",
      tip: "For process essays, chronological order is often the clearest structure." },
    { id: "p1w15", word: "transition", pos: "noun", ipa: "/trænˈzɪʃn/", emoji: "🌉",
      def: "a word or phrase that connects one idea to the next",
      ex: "The essay lacks transitions, so the reader struggles to follow the argument.",
      collocs: ["a smooth transition", "transition words", "make the transition to"],
      family: "transition (n) · transitional (adj)",
      tip: "Vary your transitions — repeating 'also' and 'but' limits your writing score." }
  ]
},
{
  id: 2, title: "Structure & Coherence", subtitle: "Paragraphs that hold together", emoji: "🏗️", color: "#34d399",
  words: [
    { id: "p2w1", word: "coherence", pos: "noun", ipa: "/koʊˈhɪrəns/", emoji: "🧭",
      def: "the state of being clear, logical, and well connected",
      ex: "A strong outline gives an essay coherence from start to finish.",
      collocs: ["logical coherence", "the coherence of the argument"],
      family: "coherent (adj) · coherently (adv) · coherence (n)",
      tip: "Coherence is about meaning connecting; cohesion is about linking words. Use both terms in analysis." },
    { id: "p2w2", word: "unity", pos: "noun", ipa: "/ˈjuːnəti/", emoji: "🎽",
      def: "the quality of forming a single, complete whole",
      ex: "Each paragraph should have unity: one main idea, fully developed.",
      collocs: ["paragraph unity", "a sense of unity"],
      family: "unite (v) · unified (adj) · unity (n)",
      tip: "A paragraph loses unity when it introduces a second unrelated idea." },
    { id: "p2w3", word: "elaborate", pos: "verb", ipa: "/ɪˈlæbəreɪt/", emoji: "🪴",
      def: "to explain something in more detail",
      ex: "The professor asked her to elaborate on her second point.",
      collocs: ["elaborate on a point", "elaborate further"],
      family: "elaboration (n) · elaborate (adj /ɪˈlæbərət/) · elaborately (adv)",
      tip: "As a verb, stress the last syllable: e-LAB-or-ate. As an adjective: e-LAB-or-ət." },
    { id: "p2w4", word: "outline", pos: "noun/verb", ipa: "/ˈaʊtlaɪn/", emoji: "🗂️",
      def: "a plan showing the main structure of a piece of writing",
      ex: "She wrote a quick outline before her timed essay.",
      collocs: ["a detailed outline", "outline the main points"],
      family: "outline (n/v)",
      tip: "60 seconds of outlining prevents mid-essay stalls — part of your speed system." },
    { id: "p2w5", word: "emphasis", pos: "noun", ipa: "/ˈemfəsɪs/", emoji: "🔆",
      def: "special importance given to something",
      ex: "The course places emphasis on critical thinking rather than memorization.",
      collocs: ["place emphasis on", "put emphasis on", "strong emphasis"],
      family: "emphasise (v) · emphasis (n) · emphatic (adj)",
      tip: "Use 'place emphasis on' — not 'give emphasis to' — in formal writing." },
    { id: "p2w6", word: "reinforce", pos: "verb", ipa: "/ˌriːɪnˈfɔːrs/", emoji: "🧱",
      def: "to make an idea, feeling, or structure stronger",
      ex: "Examples reinforce the main argument by making it concrete.",
      collocs: ["reinforce an argument", "reinforce the idea that"],
      family: "reinforcement (n) · reinforced (adj)",
      tip: "Pairs well with 'evidence', 'argument', 'impression'." },
    { id: "p2w7", word: "relevant", pos: "adjective", ipa: "/ˈreləvənt/", emoji: "🎯",
      def: "closely connected to the topic being discussed",
      ex: "Only include details that are relevant to your main claim.",
      collocs: ["relevant to", "highly relevant", "relevant evidence"],
      family: "relevance (n) · relevant (adj) · relevantly (adv) · irrelevant (adj)",
      tip: "Wrong-topic examples are one of the biggest paragraph-level score killers." },
    { id: "p2w8", word: "concise", pos: "adjective", ipa: "/kənˈsaɪs/", emoji: "✂️",
      def: "giving a lot of information clearly in few words",
      ex: "Concise sentences are easier to follow than long, tangled ones.",
      collocs: ["clear and concise", "a concise summary"],
      family: "concision (n) · concise (adj) · concisely (adv)",
      tip: "In a timed test, concise beats complex. Cut words that add nothing." },
    { id: "p2w9", word: "redundant", pos: "adjective", ipa: "/rɪˈdʌndənt/", emoji: "♻️",
      def: "not needed because it repeats something already said",
      ex: "'Free gift' is redundant because a gift is always free.",
      collocs: ["redundant information", "delete redundant words"],
      family: "redundancy (n) · redundant (adj)",
      tip: "Scan for redundancy in your proofread pass — it hides real content." },
    { id: "p2w10", word: "digress", pos: "verb", ipa: "/daɪˈɡres/", emoji: "🚶",
      def: "to move away from the main topic",
      ex: "The essay digresses into personal stories and loses its focus.",
      collocs: ["digress from the topic", "I digress"],
      family: "digression (n) · digressive (adj)",
      tip: "Signals a paragraph unity problem: every sentence must serve the main idea." },
    { id: "p2w11", word: "framework", pos: "noun", ipa: "/ˈfreɪmwɜːrk/", emoji: "🖼️",
      def: "a basic structure used to organize ideas or research",
      ex: "The T-S-C framework keeps each paragraph on track.",
      collocs: ["a theoretical framework", "provide a framework", "within this framework"],
      family: "frame (n/v) · framework (n)",
      tip: "Perfect for describing essay structures: 'a three-part framework'." },
    { id: "p2w12", word: "hierarchy", pos: "noun", ipa: "/ˈhaɪərɑːrki/", emoji: "🪜",
      def: "a system in which things are ranked by importance",
      ex: "A clear hierarchy of ideas helps readers see what matters most.",
      collocs: ["a hierarchy of ideas", "the social hierarchy"],
      family: "hierarchical (adj) · hierarchically (adv)",
      tip: "Also describes society: 'social hierarchy'. Watch the unusual spelling: hier-archy." },
    { id: "p2w13", word: "overarching", pos: "adjective", ipa: "/ˌoʊvərˈɑːrtʃɪŋ/", emoji: "🌈",
      def: "covering or affecting everything; main and all-inclusive",
      ex: "The overarching goal of the course is independent thinking.",
      collocs: ["an overarching theme", "the overarching goal"],
      family: "overarch (v) · overarching (adj)",
      tip: "Excellent for thesis sentences: 'the overarching argument of this essay'." },
    { id: "p2w14", word: "embed", pos: "verb", ipa: "/ɪmˈbed/", emoji: "📌",
      def: "to fix something firmly inside something else",
      ex: "Embed one short example inside each paragraph to support your claim.",
      collocs: ["embed evidence", "deeply embedded"],
      family: "embedded (adj) · embedding (n)",
      tip: "Use for evidence: 'embed a statistic in the reason sentence'." },
    { id: "p2w15", word: "streamline", pos: "verb", ipa: "/ˈstriːmlaɪn/", emoji: "🚿",
      def: "to make a process simpler and more efficient",
      ex: "The university streamlined its application process.",
      collocs: ["streamline a process", "streamline operations"],
      family: "streamlined (adj) · streamlining (n)",
      tip: "Great verb for recommending improvements in reports and emails." }
  ]
}
]);
