// Daily Vocabulary Centre — Packs 7-8
window.VOCAB_PACKS = (window.VOCAB_PACKS || []).concat([
{
  id: 7, title: "Time & Process", subtitle: "Plan, pace, and finish", emoji: "⏱️", color: "#fbbf24",
  words: [
    { id: "p7w1", word: "allocate", pos: "verb", ipa: "/ˈæləkeɪt/", emoji: "🗓️",
      def: "to give time, money, or resources to a particular purpose",
      ex: "Allocate two minutes for planning before you start writing.",
      collocs: ["allocate time", "allocate resources", "allocate funds to"],
      family: "allocation (n) · allocated (adj)",
      tip: "Time-management core verb: 'allocate one minute per sentence'." },
    { id: "p7w2", word: "prioritise", pos: "verb", ipa: "/praɪˈɔːrətaɪz/", emoji: "1️⃣",
      def: "to deal with the most important thing first",
      ex: "When time runs out, prioritise the longest writing task.",
      collocs: ["prioritise tasks", "prioritise effectively", "learn to prioritise"],
      family: "priority (n) · prioritisation (n)",
      tip: "UK spelling -ise. In the exam: prioritise length, then accuracy." },
    { id: "p7w3", word: "sustain", pos: "verb", ipa: "/səˈsteɪn/", emoji: "🔋",
      def: "to keep something going over time",
      ex: "Chunk-writing helps you sustain momentum for ten minutes.",
      collocs: ["sustain momentum", "sustain effort", "sustain attention"],
      family: "sustained (adj) · sustainable (adj) · sustainability (n)",
      tip: "From your L25/L28 journals — 'sustain momentum' is the key phrase." },
    { id: "p7w4", word: "deadline", pos: "noun", ipa: "/ˈdedlaɪn/", emoji: "⏰",
      def: "the latest time by which something must be finished",
      ex: "The deadline for the scholarship application is Friday.",
      collocs: ["meet a deadline", "miss a deadline", "tight deadline"],
      family: "deadline (n)",
      tip: "Common verb: MEET a deadline (not 'reach a deadline')." },
    { id: "p7w5", word: "procrastinate", pos: "verb", ipa: "/prəˈkræstɪneɪt/", emoji: "🐢",
      def: "to delay doing something until later",
      ex: "Students who procrastinate often rely on last-minute panic.",
      collocs: ["procrastinate on", "tend to procrastinate", "stop procrastinating"],
      family: "procrastination (n) · procrastinator (n)",
      tip: "Spelling: pro-cras-tin-ate. The 't' is doubled in -tin-, not 'procrastenate'." },
    { id: "p7w6", word: "efficient", pos: "adjective", ipa: "/ɪˈfɪʃnt/", emoji: "⚙️",
      def: "working well without wasting time or energy",
      ex: "A five-sentence frame makes your writing more efficient.",
      collocs: ["an efficient method", "time-efficient", "highly efficient"],
      family: "efficiency (n) · efficiently (adv)",
      tip: "Don't confuse with 'effective' (gets results) — efficient = without waste." },
    { id: "p7w7", word: "tedious", pos: "adjective", ipa: "/ˈtiːdiəs/", emoji: "😑",
      def: "boring because it lasts too long or repeats too much",
      ex: "Copying notes by hand is tedious, but it aids memory.",
      collocs: ["a tedious task", "tedious process"],
      family: "tedium (n) · tediously (adv)",
      tip: "One of your old pronunciation flags: TEE-dee-us (/ˈtiːdiəs/)." },
    { id: "p7w8", word: "meticulous", pos: "adjective", ipa: "/məˈtɪkjələs/", emoji: "🔬",
      def: "extremely careful about details",
      ex: "Meticulous proofreading catches the spelling errors examiners notice.",
      collocs: ["meticulous attention to detail", "meticulous planning"],
      family: "meticulously (adv) · meticulousness (n)",
      tip: "Compliment word: 'meticulous attention to detail'." },
    { id: "p7w9", word: "methodical", pos: "adjective", ipa: "/məˈθɑːdɪkl/", emoji: "🧭",
      def: "done in a careful, ordered way",
      ex: "Adopting a methodical approach prevents panic in the final minutes.",
      collocs: ["a methodical approach", "methodical process"],
      family: "method (n) · methodically (adv)",
      tip: "Methodical = step-by-step and organised. Describe your writing system." },
    { id: "p7w10", word: "feasible", pos: "adjective", ipa: "/ˈfiːzəbl/", emoji: "🛠️",
      def: "possible and practical to do",
      ex: "A shorter, focused essay is more feasible than a perfect one.",
      collocs: ["a feasible option", "technically feasible", "not feasible"],
      family: "feasibility (n) · feasibly (adv)",
      tip: "Use in recommendations: 'the most feasible solution is…'." },
    { id: "p7w11", word: "sufficient", pos: "adjective", ipa: "/səˈfɪʃnt/", emoji: "🍽️",
      def: "enough for a particular purpose",
      ex: "One example is not sufficient to prove a general claim.",
      collocs: ["sufficient evidence", "sufficient time", "sufficient attention"],
      family: "sufficiency (n) · sufficiently (adv) · insufficient (adj)",
      tip: "Prefer 'sufficient' over 'enough' in formal writing." },
    { id: "p7w12", word: "anticipate", pos: "verb", ipa: "/ænˈtɪsɪpeɪt/", emoji: "🔮",
      def: "to expect something and prepare for it",
      ex: "Good test-takers anticipate difficult questions and stay calm.",
      collocs: ["anticipate problems", "anticipate the outcome", "as anticipated"],
      family: "anticipation (n) · anticipated (adj)",
      tip: "STRONGER than 'expect' — it implies preparation too." },
    { id: "p7w13", word: "contingency", pos: "noun", ipa: "/kənˈtɪndʒənsi/", emoji: "🧯",
      def: "a plan for a possible future problem",
      ex: "Have a contingency plan if the recording fails.",
      collocs: ["a contingency plan", "contingency planning", "as a contingency"],
      family: "contingent (adj)",
      tip: "Exam application: if time runs short, what is Plan B?" },
    { id: "p7w14", word: "sequence", pos: "noun/verb", ipa: "/ˈsiːkwəns/", emoji: "🔢",
      def: "the order in which things happen or are arranged",
      ex: "The paragraph follows a clear sequence: point, example, comment.",
      collocs: ["in sequence", "a logical sequence", "sequence of events"],
      family: "sequential (adj) · sequentially (adv)",
      tip: "For process writing: 'the process follows this sequence'." },
    { id: "p7w15", word: "compress", pos: "verb", ipa: "/kəmˈpres/", emoji: "🗜️",
      def: "to make something smaller or shorter",
      ex: "You must compress two ideas into one sentence here.",
      collocs: ["compress information", "compress time", "highly compressed"],
      family: "compression (n) · compressed (adj)",
      tip: "Time-management idea: compress planning, not proofreading." }
  ]
},
{
  id: 8, title: "Capstone Mix + Spelling Traps", subtitle: "The words you've used — plus the ones that bite", emoji: "🏁", color: "#c084fc",
  words: [
    { id: "p8w1", word: "comprehensive", pos: "adjective", ipa: "/ˌkɑːmprɪˈhensɪv/", emoji: "🗺️",
      def: "complete and including everything necessary",
      ex: "The report offers a comprehensive review of the research.",
      collocs: ["a comprehensive review", "comprehensive analysis", "comprehensive approach"],
      family: "comprehend (v) · comprehension (n) · comprehensively (adv)",
      tip: "Don't confuse with 'comprehensible' (easy to understand)." },
    { id: "p8w2", word: "deliberate", pos: "adjective/verb", ipa: "/dɪˈlɪbərət/", emoji: "🎯",
      def: "done intentionally and carefully",
      ex: "Deliberate practice, not repetition, improves writing.",
      collocs: ["deliberate practice", "a deliberate choice", "deliberately ambiguous"],
      family: "deliberately (adv) · deliberation (n) · deliberate (v /dɪˈlɪbəreɪt/)",
      tip: "Adjective stress: de-LIB-er-ət. Verb (to discuss): de-LIB-er-ate." },
    { id: "p8w3", word: "strategic", pos: "adjective", ipa: "/strəˈtiːdʒɪk/", emoji: "♟️",
      def: "planned carefully to achieve a goal",
      ex: "Strategic use of transitions improves your writing score.",
      collocs: ["strategic approach", "strategic decision", "strategically placed"],
      family: "strategy (n) · strategically (adv)",
      tip: "From your journals. 'Strategic' = planned for effect; 'strategical' is not a word." },
    { id: "p8w4", word: "systematic", pos: "adjective", ipa: "/ˌsɪstəˈmætɪk/", emoji: "🗄️",
      def: "done according to a fixed plan or system",
      ex: "Keep a systematic record of your recurring errors.",
      collocs: ["a systematic approach", "systematic review", "systematically check"],
      family: "system (n) · systematically (adv)",
      tip: "Systematic = organised method. Compare: systematic (careful order)." },
    { id: "p8w5", word: "proactive", pos: "adjective", ipa: "/ˌproʊˈæktɪv/", emoji: "🏃",
      def: "acting before a problem happens, not waiting for it",
      ex: "Being proactive about deadlines prevents last-minute panic.",
      collocs: ["proactive approach", "take a proactive role", "proactively address"],
      family: "proactively (adv) · proactivity (n)",
      tip: "Opposite of reactive. Great for describing your study habits." },
    { id: "p8w6", word: "recurring", pos: "adjective", ipa: "/rɪˈkɜːrɪŋ/", emoji: "🔁",
      def: "happening again and again",
      ex: "Spelling under pressure is a recurring issue in timed essays.",
      collocs: ["a recurring problem", "recurring theme", "recurring errors"],
      family: "recur (v) · recurrence (n)",
      tip: "Double 'r' in the middle: re-CURR-ing. Not 'reccuring'." },
    { id: "p8w7", word: "proficiency", pos: "noun", ipa: "/prəˈfɪʃnsi/", emoji: "🎓",
      def: "the ability to do something well; skill level",
      ex: "Students can demonstrate proficiency through real projects.",
      collocs: ["language proficiency", "a high level of proficiency", "demonstrate proficiency"],
      family: "proficient (adj) · proficiently (adv)",
      tip: "Spelling: pro-fi-cien-cy (-ficient, not -ficent)." },
    { id: "p8w8", word: "threshold", pos: "noun", ipa: "/ˈθreʃhoʊld/", emoji: "🚪",
      def: "a level or point at which something changes",
      ex: "A score above the threshold guarantees an interview.",
      collocs: ["reach a threshold", "above the threshold", "threshold level"],
      family: "threshold (n)",
      tip: "Spelling: thresh-OLD (not 'threshhold'). Your pronunciation flag: THRESH-old." },
    { id: "p8w9", word: "exemplify", pos: "verb", ipa: "/ɪɡˈzemplɪfaɪ/", emoji: "🌟",
      def: "to be a typical example of something; to illustrate",
      ex: "Her essay exemplifies how a short response can still be persuasive.",
      collocs: ["exemplify a trend", "perfectly exemplifies", "best exemplified by"],
      family: "example (n) · exemplary (adj) · exemplification (n)",
      tip: "Formal upgrade for 'for example'. Use in analysis, not as a transition word." },
    { id: "p8w10", word: "ensure", pos: "verb", ipa: "/ɪnˈʃʊr/", emoji: "🔒",
      def: "to make certain that something happens",
      ex: "Proofread to ensure that no spelling errors remain.",
      collocs: ["ensure that", "ensure accuracy", "ensure compliance"],
      family: "assurance (n) · assured (adj)",
      tip: "SPELLING TRAP: it's en-SURE, never 'desure' or 'insure' (insure = for money)." },
    { id: "p8w11", word: "psychology", pos: "noun", ipa: "/saɪˈkɑːlədʒi/", emoji: "🧠",
      def: "the scientific study of the mind and behaviour",
      ex: "The psychology of decision-making fascinates behavioural economists.",
      collocs: ["consumer psychology", "the psychology of", "clinical psychology"],
      family: "psychological (adj) · psychologist (n) · psychologically (adv)",
      tip: "SPELLING TRAP: psy-CHO-lo-gy (silent p). You once wrote 'phychology' to a psychology professor!" },
    { id: "p8w12", word: "useful", pos: "adjective", ipa: "/ˈjuːsfl/", emoji: "🧰",
      def: "helpful for doing something",
      ex: "Feedback is most useful when it is specific.",
      collocs: ["a useful tool", "extremely useful", "useful for"],
      family: "use (v/n) · usefully (adv) · usefulness (n)",
      tip: "SPELLING TRAP: use-FUL — one l. You've written 'usefull' before; the proofread pass exists for this." },
    { id: "p8w13", word: "source", pos: "noun", ipa: "/sɔːrs/", emoji: "📚",
      def: "the place something comes from; a reference in research",
      ex: "Always cite a reliable source for statistics.",
      collocs: ["a reliable source", "primary source", "cite a source"],
      family: "source (n/v)",
      tip: "SPELLING TRAP: s-OU-rce. 'Sourses' is the error you've made under time pressure." },
    { id: "p8w14", word: "research", pos: "noun/verb", ipa: "/rɪˈsɜːrtʃ/", emoji: "🔭",
      def: "careful study of a subject to discover new facts",
      ex: "The research suggests that feedback improves performance.",
      collocs: ["conduct research", "a piece of research", "research findings"],
      family: "researcher (n) · researched (adj)",
      tip: "NOUN TRAP: 'research' is uncountable — 'some research', not 'researches'. Verb form is fine: 'she researches…'." },
    { id: "p8w15", word: "paramount", pos: "adjective", ipa: "/ˈpærəmaʊnt/", emoji: "👑",
      def: "more important than anything else",
      ex: "In academic writing, clarity is paramount.",
      collocs: ["of paramount importance", "paramount concern"],
      family: "paramount (adj)",
      tip: "Learned phrasing: 'of paramount importance'. Very high-impact in conclusions." }
  ]
}
]);
