// Daily Vocabulary Centre — Packs 5-6
window.VOCAB_PACKS = (window.VOCAB_PACKS || []).concat([
{
  id: 5, title: "Cause, Effect & Change", subtitle: "Describe impact like an analyst", emoji: "🌊", color: "#f87171",
  words: [
    { id: "p5w1", word: "mitigate", pos: "verb", ipa: "/ˈmɪtɪɡeɪt/", emoji: "🩹",
      def: "to make something bad less severe",
      ex: "Planting trees can mitigate the effects of urban heat.",
      collocs: ["mitigate the impact", "mitigate risk", "mitigate climate change"],
      family: "mitigation (n) · mitigating (adj)",
      tip: "Spelling: mit-i-gate. Pairs with impact, risk, damage, effects." },
    { id: "p5w2", word: "exacerbate", pos: "verb", ipa: "/ɪɡˈzæsərbeɪt/", emoji: "🔥",
      def: "to make a problem worse",
      ex: "Cutting public transport would exacerbate traffic congestion.",
      collocs: ["exacerbate the problem", "exacerbate inequality"],
      family: "exacerbation (n) · exacerbated (adj)",
      tip: "The antonym of mitigate. Spelling trap: exa-cer-bate, not 'exaserbate'." },
    { id: "p5w3", word: "foster", pos: "verb", ipa: "/ˈfɔːstər/", emoji: "🌱",
      def: "to encourage something good to develop",
      ex: "Group projects foster collaboration and communication skills.",
      collocs: ["foster creativity", "foster a sense of", "foster development"],
      family: "fostering (n)",
      tip: "Positive verb for outcomes: foster growth, trust, innovation, inclusion." },
    { id: "p5w4", word: "hinder", pos: "verb", ipa: "/ˈhɪndər/", emoji: "🚧",
      def: "to make progress difficult",
      ex: "Constant notifications hinder students' ability to focus.",
      collocs: ["hinder progress", "hinder development", "hinder learning"],
      family: "hindrance (n) · hindered (adj)",
      tip: "Softer than 'prevent': hinder slows things down; prevent stops them." },
    { id: "p5w5", word: "alleviate", pos: "verb", ipa: "/əˈliːvieɪt/", emoji: "🧊",
      def: "to make pain or a problem less severe",
      ex: "Flexible deadlines alleviate stress during exam season.",
      collocs: ["alleviate poverty", "alleviate pressure", "alleviate symptoms"],
      family: "alleviation (n)",
      tip: "Very close to mitigate; often used with poverty, stress, pressure." },
    { id: "p5w6", word: "deteriorate", pos: "verb", ipa: "/dɪˈtɪriəreɪt/", emoji: "📉",
      def: "to become worse over time",
      ex: "Air quality deteriorated sharply after the new factory opened.",
      collocs: ["conditions deteriorate", "deteriorating situation", "deteriorate rapidly"],
      family: "deterioration (n) · deteriorating (adj)",
      tip: "Intransitive: things deteriorate; you don't 'deteriorate' something. Don't confuse with 'deteriorate/deterorate' spelling." },
    { id: "p5w7", word: "catalyst", pos: "noun", ipa: "/ˈkætəlɪst/", emoji: "⚡",
      def: "something that causes or speeds up change",
      ex: "The pandemic acted as a catalyst for online education.",
      collocs: ["a catalyst for change", "act as a catalyst"],
      family: "catalyse (v) · catalytic (adj)",
      tip: "Pattern: 'a catalyst for + noun'. Strong for cause-effect essays." },
    { id: "p5w8", word: "ramifications", pos: "noun", ipa: "/ˌræmɪfɪˈkeɪʃnz/", emoji: "🌐",
      def: "the complex results or consequences of an action",
      ex: "The decision had serious ramifications for rural communities.",
      collocs: ["serious ramifications", "long-term ramifications", "have ramifications for"],
      family: "ramify (v)",
      tip: "Usually plural. Bigger and wider than 'results' — use for consequences of decisions." },
    { id: "p5w9", word: "inevitable", pos: "adjective", ipa: "/ɪnˈevɪtəbl/", emoji: "⏳",
      def: "certain to happen; impossible to avoid",
      ex: "Some job displacement is inevitable as automation spreads.",
      collocs: ["an inevitable result", "almost inevitable", "the inevitable consequence"],
      family: "inevitability (n) · inevitably (adv)",
      tip: "'The inevitable consequence of X is Y' — a ready-made exam frame." },
    { id: "p5w10", word: "detrimental", pos: "adjective", ipa: "/ˌdetrɪˈmentl/", emoji: "⚠️",
      def: "causing harm or damage",
      ex: "Sleep deprivation is detrimental to academic performance.",
      collocs: ["detrimental to health", "a detrimental effect", "detrimental impact"],
      family: "detriment (n) · detrimentally (adv)",
      tip: "A L26 precision upgrade for 'bad'. Pattern: 'detrimental to + noun'." },
    { id: "p5w11", word: "profound", pos: "adjective", ipa: "/prəˈfaʊnd/", emoji: "🔊",
      def: "very great, deep, or intense",
      ex: "AI has had a profound impact on how research is conducted.",
      collocs: ["a profound impact", "profound implications", "a profound change"],
      family: "profoundly (adv) · profundity (n)",
      tip: "Strong collocational partner for impact, effect, implications, change." },
    { id: "p5w12", word: "trigger", pos: "verb", ipa: "/ˈtrɪɡər/", emoji: "🎢",
      def: "to cause something to start happening",
      ex: "A single viral post can trigger a wave of misinformation.",
      collocs: ["trigger a reaction", "trigger debate", "trigger a decline"],
      family: "trigger (n/v) · triggered (adj)",
      tip: "More immediate than 'cause': it starts the chain reaction." },
    { id: "p5w13", word: "curtail", pos: "verb", ipa: "/kɜːrˈteɪl/", emoji: "✂️",
      def: "to reduce or limit something",
      ex: "Budget cuts curtailed the university's research programs.",
      collocs: ["curtail spending", "curtail freedoms", "curtail operations"],
      family: "curtailment (n)",
      tip: "Formal alternative to 'cut back'. Pairs with spending, rights, activities." },
    { id: "p5w14", word: "escalate", pos: "verb", ipa: "/ˈeskəleɪt/", emoji: "🪜",
      def: "to become more serious or intense",
      ex: "Without intervention, the dispute escalated rapidly.",
      collocs: ["escalate quickly", "escalating costs", "escalate into"],
      family: "escalation (n) · escalating (adj)",
      tip: "Also for communication: 'escalate a problem to management'." },
    { id: "p5w15", word: "unprecedented", pos: "adjective", ipa: "/ʌnˈpresɪdentɪd/", emoji: "🆕",
      def: "never having happened before",
      ex: "The move to remote work was unprecedented in scale.",
      collocs: ["an unprecedented level", "unprecedented growth", "unprecedented situation"],
      family: "precedent (n) · unprecedented (adj)",
      tip: "C1 favourite. Means 'no precedent exists' — strong but don't overuse." }
  ]
},
{
  id: 6, title: "Academic Analysis Verbs", subtitle: "Word list core — research & data", emoji: "🧪", color: "#22d3ee",
  words: [
    { id: "p6w1", word: "derive", pos: "verb", ipa: "/dɪˈraɪv/", emoji: "🌿",
      def: "to obtain something from a source; to come from",
      ex: "The findings derive from three years of fieldwork.",
      collocs: ["derive from", "derive conclusions", "derive benefit from"],
      family: "derivation (n) · derived (adj) · derivative (n/adj)",
      tip: "Pattern: 'derive X from Y'. Common in methods descriptions." },
    { id: "p6w2", word: "indicate", pos: "verb", ipa: "/ˈɪndɪkeɪt/", emoji: "👉",
      def: "to show or suggest that something is true",
      ex: "The results indicate a clear link between sleep and memory.",
      collocs: ["results indicate", "evidence indicates", "strongly indicate"],
      family: "indication (n) · indicator (n) · indicative (adj)",
      tip: "More cautious than 'prove'. Perfect for reporting data honestly." },
    { id: "p6w3", word: "constitute", pos: "verb", ipa: "/ˈkɑːnstɪtuːt/", emoji: "🧩",
      def: "to be or make up a whole",
      ex: "Women constitute over half of the university's graduates.",
      collocs: ["constitute a majority", "constitute a threat", "constitute evidence"],
      family: "constitution (n) · constituent (n/adj)",
      tip: "Pattern: 'X constitutes Y' = X forms/is Y. Very formal." },
    { id: "p6w4", word: "assess", pos: "verb", ipa: "/əˈses/", emoji: "📏",
      def: "to judge or evaluate something carefully",
      ex: "The study assesses the impact of class size on achievement.",
      collocs: ["assess the impact", "assess the situation", "difficult to assess"],
      family: "assessment (n) · assessor (n)",
      tip: "Use for evaluation essays: assess costs and benefits." },
    { id: "p6w5", word: "interpret", pos: "verb", ipa: "/ɪnˈtɜːrprət/", emoji: "🔭",
      def: "to explain the meaning of something",
      ex: "Critics interpret the data differently.",
      collocs: ["interpret the results", "be interpreted as", "interpret evidence"],
      family: "interpretation (n) · interpretive (adj) · misinterpret (v)",
      tip: "Reading questions hinge on interpretation — support it with the text." },
    { id: "p6w6", word: "attribute", pos: "verb", ipa: "/əˈtrɪbjuːt/", emoji: "🏷️",
      def: "to say that something is caused by something else",
      ex: "She attributes the improvement to better teaching, not more tests.",
      collocs: ["attribute A to B", "attribute success to"],
      family: "attribution (n) · attributed (adj)",
      tip: "Pattern: 'attribute X to Y'. Stress: verb /əˈtrɪbjuːt/, noun /ˈætrɪbjuːt/." },
    { id: "p6w7", word: "correlate", pos: "verb", ipa: "/ˈkɔːrəleɪt/", emoji: "📊",
      def: "to have a connection in which one thing changes with another",
      ex: "Income strongly correlates with access to higher education.",
      collocs: ["correlate with", "highly correlated", "correlation between"],
      family: "correlation (n) · correlated (adj)",
      tip: "Remember: correlation ≠ causation. A classic critical-thinking point." },
    { id: "p6w8", word: "comprise", pos: "verb", ipa: "/kəmˈpraɪz/", emoji: "🍰",
      def: "to consist of or be made up of",
      ex: "The sample comprises 500 students from five countries.",
      collocs: ["comprise a majority", "be comprised of", "comprise several parts"],
      family: "comprised (adj)",
      tip: "The whole comprises the parts; the parts compose the whole." },
    { id: "p6w9", word: "illustrate", pos: "verb", ipa: "/ˈɪləstreɪt/", emoji: "🖍️",
      def: "to explain or make something clear by giving an example",
      ex: "The graph illustrates the decline in newspaper readership.",
      collocs: ["illustrate a point", "clearly illustrate", "as illustrated by"],
      family: "illustration (n) · illustrative (adj)",
      tip: "Use when introducing examples: 'This trend is illustrated by…'." },
    { id: "p6w10", word: "examine", pos: "verb", ipa: "/ɪɡˈzæmɪn/", emoji: "🔎",
      def: "to look at something carefully in order to understand it",
      ex: "The essay examines both sides of the debate.",
      collocs: ["examine the evidence", "examine how", "closely examine"],
      family: "examination (n) · examiner (n)",
      tip: "Good for stating scope: 'This essay examines…'." },
    { id: "p6w11", word: "evaluate", pos: "verb", ipa: "/ɪˈvæljueɪt/", emoji: "🧾",
      def: "to judge the value or quality of something",
      ex: "We must evaluate whether the benefits justify the costs.",
      collocs: ["evaluate the effectiveness", "critically evaluate", "evaluate options"],
      family: "evaluation (n) · evaluative (adj)",
      tip: "Score-boosting C1 verb: evaluate, don't just describe." },
    { id: "p6w12", word: "infer", pos: "verb", ipa: "/ɪnˈfɜːr/", emoji: "🧠",
      def: "to reach a conclusion using evidence and reasoning",
      ex: "From the passage, we can infer that the author doubts the policy.",
      collocs: ["infer from", "reasonably infer", "it can be inferred that"],
      family: "inference (n) · inferential (adj)",
      tip: "Never quote when you infer — the answer is implied, not written. Reading gold." },
    { id: "p6w13", word: "demonstrate", pos: "verb", ipa: "/ˈdemənstreɪt/", emoji: "🎬",
      def: "to show clearly that something is true",
      ex: "The experiment demonstrates that the method works under pressure.",
      collocs: ["demonstrate competence", "demonstrate that", "clearly demonstrate"],
      family: "demonstration (n) · demonstrable (adj) · demonstrably (adv)",
      tip: "Pairs with your collocation 'demonstrate competence'. Also common: 'research demonstrates'." },
    { id: "p6w14", word: "hypothesise", pos: "verb", ipa: "/haɪˈpɑːθəsaɪz/", emoji: "💭",
      def: "to suggest an explanation that is not yet proven",
      ex: "Researchers hypothesise that the effect fades after six months.",
      collocs: ["hypothesise that", "hypothesise about"],
      family: "hypothesis (n) · hypothetical (adj)",
      tip: "UK spelling -ise. States a testable claim, not a fact." },
    { id: "p6w15", word: "verify", pos: "verb", ipa: "/ˈverɪfaɪ/", emoji: "☑️",
      def: "to check that something is true or accurate",
      ex: "Always verify statistics before citing them.",
      collocs: ["verify the results", "independently verify", "difficult to verify"],
      family: "verification (n) · verifiable (adj)",
      tip: "For reading and research: verify = confirm with a second source." }
  ]
}
]);
